import Head from 'next/head';
import React from 'react';

type MetaHeadType = {
    title: string
}

const MetaHead = (props: MetaHeadType) => {
    const { title } = props
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
};

export default MetaHead;